"use client";

import Link from "next/link";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[#F8F5EF] text-[#3F2D1D]">
      <div className="max-w-3xl mx-auto px-6 py-12">
        {/* Header */}
        <div className="mb-10">
          <Link href="/" className="text-xs uppercase tracking-widest text-amber-700 font-bold hover:text-amber-900 transition-colors">
            ← Back to DivyaDrishti
          </Link>
          <h1 className="mt-6 text-4xl font-serif font-light tracking-wide">Terms of Service</h1>
          <p className="mt-2 text-sm text-[#3F2D1D]/60">Effective date: July 6, 2026</p>
        </div>

        <div className="prose prose-sm max-w-none text-[#3F2D1D]/85 space-y-8 leading-relaxed">

          <section>
            <h2 className="text-lg font-serif font-semibold text-[#3F2D1D] mb-3">1. Acceptance of Terms</h2>
            <p>
              By downloading, installing, or using DivyaDrishti (the &ldquo;App&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-serif font-semibold text-[#3F2D1D] mb-3">2. Nature of the Service</h2>
            <p>
              DivyaDrishti provides Vedic astrology-based guidance for personal reflection, self-awareness, and life planning. The guidance generated by the App, including all AI-powered responses, Dasha analyses, transit readings, and Panchang information, is intended for <strong>informational and entertainment purposes only</strong>.
            </p>
            <p className="mt-3">
              DivyaDrishti is <strong>not a substitute for</strong> professional medical, legal, financial, psychological, or any other licensed professional advice. Do not make major life decisions — including medical, financial, or legal decisions — based solely on content provided by the App.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-serif font-semibold text-[#3F2D1D] mb-3">3. Account Registration</h2>
            <p>
              You must create an account to use DivyaDrishti. You are responsible for:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Providing accurate registration information including your name and email address.</li>
              <li>Keeping your password confidential and not sharing it with others.</li>
              <li>All activity that occurs under your account.</li>
            </ul>
            <p className="mt-3">
              You must be at least 13 years of age to create an account. By registering, you confirm that you meet this age requirement.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-serif font-semibold text-[#3F2D1D] mb-3">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use the App for any unlawful purpose or in violation of any applicable laws.</li>
              <li>Attempt to gain unauthorized access to any part of the App or its backend systems.</li>
              <li>Reverse-engineer, decompile, or disassemble the App.</li>
              <li>Impersonate any person or entity or misrepresent your affiliation with any person or entity.</li>
              <li>Submit false, misleading, or harmful content through the App&apos;s chat or reflection features.</li>
              <li>Use automated means (bots, scrapers) to access the App at a rate exceeding normal human usage.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-serif font-semibold text-[#3F2D1D] mb-3">5. Intellectual Property</h2>
            <p>
              All content, design, code, and astrological algorithms within DivyaDrishti are the intellectual property of DivyaDrishti and its developer. The App uses open-source components (including Swiss Ephemeris under the GNU GPL license) where indicated. The Vedic astrological tradition itself is in the public domain.
            </p>
            <p className="mt-3">
              You retain ownership of the personal data you submit (birth details, reflections). By submitting this data, you grant us a limited, non-exclusive licence to process it solely to provide the service to you.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-serif font-semibold text-[#3F2D1D] mb-3">6. Disclaimer of Warranties</h2>
            <p>
              THE APP IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ASTROLOGICAL INTERPRETATIONS AND AI-GENERATED GUIDANCE ARE PROVIDED WITHOUT GUARANTEE OF ACCURACY OR FITNESS FOR ANY PARTICULAR PURPOSE.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-serif font-semibold text-[#3F2D1D] mb-3">7. Limitation of Liability</h2>
            <p>
              TO THE FULLEST EXTENT PERMITTED BY LAW, DIVYADRISHTI AND ITS DEVELOPER SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE THE APP, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT SHALL OUR TOTAL LIABILITY EXCEED THE AMOUNT YOU PAID FOR THE APP IN THE 12 MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-serif font-semibold text-[#3F2D1D] mb-3">8. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at our discretion if we believe you have violated these Terms. You may delete your account at any time by contacting us at <a href="mailto:telangrahul2026@gmail.com" className="text-amber-700 underline">telangrahul2026@gmail.com</a>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-serif font-semibold text-[#3F2D1D] mb-3">9. Governing Law</h2>
            <p>
              These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Hyderabad, Telangana, India.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-serif font-semibold text-[#3F2D1D] mb-3">10. Changes to Terms</h2>
            <p>
              We may revise these Terms from time to time. Material changes will be communicated via the App or by email. Your continued use of the App after changes take effect constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-serif font-semibold text-[#3F2D1D] mb-3">11. Contact</h2>
            <p>
              For any questions regarding these Terms, please contact us at <a href="mailto:telangrahul2026@gmail.com" className="text-amber-700 underline">telangrahul2026@gmail.com</a>.
            </p>
          </section>

        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-[#F1E7D0] flex items-center justify-between text-[10px] uppercase tracking-widest text-[#3F2D1D]/40">
          <span>DivyaDrishti</span>
          <Link href="/privacy" className="hover:text-amber-700 transition-colors">Privacy Policy →</Link>
        </div>
      </div>
    </div>
  );
}
